name: eastern_trust
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  typed_data: ^1.3.0
#  win32: ^5.9.0
  dotted_line: ^3.1.0
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.2.0
  flutter_svg_provider: ^1.0.3
  #dropdown_formfield: ^0.1.4
  http: ^1.5.0
  lottie: ^3.3.1
  carousel_slider: ^5.1.1

  file_picker: ^10.2.3
  image_picker: ^1.1.2
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  webview_flutter: ^4.13.0
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.17.0
  font_awesome_flutter: ^10.4.0
  share_plus: ^11.0.0
  animated_bottom_navigation_bar: ^1.4.0
  auto_size_text: ^3.0.0
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  package_info_plus: ^8.3.0
  bottom_navy_bar: ^6.0.0
  simple_animations: ^5.2.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.0.0+2
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^17.0.0
  firebase_analytics: ^10.0.8
  firebase_core: ^2.4.0
  awesome_dialog: ^3.0.2
  circular_countdown_timer: ^0.2.3
  dio: ^5.9.0
  otp_timer_button: ^1.1.0
  percent_indicator: ^4.2.2
  connectivity_plus: ^6.1.4
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  qr_flutter: ^4.1.0
#  image_downloader: ^0.31.0
  flutter_exif_rotation: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo/eastern_logo.png"

flutter_native_splash:
  color: "#FFFFFF"          # background color
  image: assets/images/launcher_img.png   # your splash image path

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/menu/
    - assets/images/app_logo/
    - assets/images/common/
    - assets/images/transfer/
    - assets/icons/
    - assets/animation/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700

    - family: SF-UI-Display-Regular
      fonts:
        - asset: assets/fonts/SF-UI-Display-Regular.ttf